<a href="https://colab.research.google.com/github/vaaibhavsharma/pyCJ/blob/main/pythonLab/Experiment_15.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
x = np.array([3, 7, 9, 4, 2])
print("Original array: " + str(x))
x = x[::-1]
print("Reversed array: " + str(x))


Original array: [3 7 9 4 2]
Reversed array: [2 4 9 7 3]


In [5]:
import numpy as np
a = np.array([[1, 7, 3], [5, 4, 9]])
print('Shape = ' + str(a.shape))
print('Type = ' + str(type(a)))
print('Data type = ' + str(a.dtype ))

Shape = (2, 3)
Type = <class 'numpy.ndarray'>
Data type = int64


In [2]:
import numpy as np
x =  np.diagflat([1,1,1,1,1])
print(x)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [6]:
import numpy as np
A = np.array([[7, 1, 9], [3, -1, 2], [-2, 1, 1]])
B = np.array([[3, 3, 1], [5, -1, 3], [-7, 5, 1]])
R= np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
Sum=A+B
Mul = A.dot(B)
print('Sum: \n'+ str(Sum))
print('Multiplication: \n'+ str(Mul))

Sum: 
[[10  4 10]
 [ 8 -2  5]
 [-9  6  2]]
Multiplication: 
[[-37  65  19]
 [-10  20   2]
 [ -8  -2   2]]


In [3]:
import numpy as np 
a = np.array([0,30,45,60,90]) 
sin = np.sin(a*np.pi/180) 
cos = np.cos(a*np.pi/180)
tan = np.tan(a*np.pi/180)
print('Array containing sine values:' + str(sin) )
print('')
print('Array containing cos values:' + str(cos) )
print('')
print('Array containing tan values:' + str(tan) )

Array containing sine values:[0.         0.5        0.70710678 0.8660254  1.        ]

Array containing cos values:[1.00000000e+00 8.66025404e-01 7.07106781e-01 5.00000000e-01
 6.12323400e-17]

Array containing tan values:[0.00000000e+00 5.77350269e-01 1.00000000e+00 1.73205081e+00
 1.63312394e+16]


In [4]:
import numpy as np
a = np.array([4, 3, 5, 1])
print("Original array: "+ str(a))
b = np.exp(a)
print("e^x:"+ str(b))

Original array: [4 3 5 1]
e^x:[ 54.59815003  20.08553692 148.4131591    2.71828183]
